### ISSUE TITLE
Update API Docs for Payments v1

### ISSUE THREAD

**Issue by brentonheble** [Fastlane-LLC/xpayoff-docs#50]
See **[notion doc](https://www.notion.so/lossexpress/Changes-to-API-docs-for-Payments-v1-fcbf7720ba16428c97d4d0bf26fd5cf1?pvs=4)** that we are drafting the changes

**Comment by harpality** [comment]
@BillyB0t here's a screenshot of the title transfer stuff added, just fyi

<img width="2007" alt="Screenshot 2023-06-29 at 18 18 42" src="https://github.com/Fastlane-LLC/xpayoff-docs/assets/25518370/c071a6c4-3d66-49dd-96b9-fb0dd1504263">

**Comment by brentonheble** [comment]
@harpalassi the added Title Transfer stuff looks good. go ahead and push this out. We still need to fix the "Payoff Status" to "Payoff Quote" in the docs, but I'll have that be a separate thing next sprint.
